name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Install dependencies 
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: Build Jekyll site
      run: |
        bundle exec jekyll build
    - name: Copy to droplet
      run: |
        echo '${{ secrets.SSHKEY }}' > id_rsa
        rsync -avzP -e "ssh -i id_rsa" _site/ ${{ secrets.USERNAME }}@${{ secrets.HOSTNAME }}:${{ secrets.DESTFOLDER }}

